package cipherPackage;

/**
 *
 * @author dinht
 */
public class JFVegenere extends javax.swing.JFrame {

    /** Creates new form JFVegenere */
    public JFVegenere() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        geneKeyTextField1 = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        encButton1 = new javax.swing.JButton();
        label6 = new java.awt.Label();
        decButton1 = new javax.swing.JButton();
        geneKeyButton1 = new javax.swing.JButton();
        keyTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        outputTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vegenera Cipher");

        geneKeyTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label4.setText("Input");

        label5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label5.setText("Output");

        encButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        encButton1.setText("Encrypt");
        encButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encButton1ActionPerformed(evt);
            }
        });

        label6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label6.setText("Key");

        decButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        decButton1.setText("Decrypt");
        decButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decButton1ActionPerformed(evt);
            }
        });

        geneKeyButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        geneKeyButton1.setText("Generate key");
        geneKeyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geneKeyButton1ActionPerformed(evt);
            }
        });

        keyTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        inputTextArea1.setColumns(20);
        inputTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inputTextArea1.setRows(5);
        jScrollPane3.setViewportView(inputTextArea1);

        outputTextArea1.setColumns(20);
        outputTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        outputTextArea1.setRows(5);
        jScrollPane4.setViewportView(outputTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(geneKeyButton1)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keyTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(geneKeyTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(decButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(encButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encButton1)
                        .addGap(25, 25, 25)
                        .addComponent(decButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keyTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geneKeyButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(geneKeyTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encButton1ActionPerformed
        String key = geneKeyTextField1.getText();
        String inText = inputTextArea1.getText();
        String cipherText = encrypt(inText, key);
        outputTextArea1.setText(cipherText);
    }//GEN-LAST:event_encButton1ActionPerformed

    private void decButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decButton1ActionPerformed
        String key = geneKeyTextField1.getText();
        String inText = inputTextArea1.getText();
        String plainText = decrypt(inText, key);
        outputTextArea1.setText(plainText);
    }//GEN-LAST:event_decButton1ActionPerformed
    static String generateKey(String str, String key) {                         //phương thức tạo key
        int x = str.length();

        for (int i = 0;; i++) {                                                 //lặp vô hạn cho đén khi độ dài key = đọ dài chuỗi mã hóa
            if (x == i) {
                i = 0;
            }
            if (key.length() == str.length()) {
                break;
            }
            key += (key.charAt(i));                                             //chuỗi key sẽ tự cộng các ký tự của chính nó
        }
        return key;                                                             //trả về key hoàn chỉnh có độ dài bằng plain text 
    }

    static String encrypt(String str, String key) {                             //phương thức encrypt
        String cipherText = "";
        for (int i = 0; i < str.length(); i++) {                                //vòng lặp xét 2 ký tự của plain text và key tại 1 vị trí
            int x = (str.charAt(i) + key.charAt(i) - 2 * 'a') % 26;             //-2*'a' là để x nằm trong phạm vi từ 0->25 để khi ánh xạ sẽ đúng giá trị
            x += 'a';
            cipherText += (char) (x);
        }
        return cipherText;
    }

    static String decrypt(String cipher_text, String key) {
        String plainText = "";
        for (int i = 0; i < cipher_text.length() && i < key.length(); i++) {    //phương thức decrypt hoạt động tương tự ecrypt    
            int x = (cipher_text.charAt(i) - key.charAt(i) + 26) % 26;          //-26 cũng để cgo giá trị nàm trong khoảng 0->26 phục vụ cho ánh xạ
            x += 'a';
            plainText += (char) (x);
        }
        return plainText;
    }

    private void geneKeyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geneKeyButton1ActionPerformed
        String keyWord = keyTextField1.getText();
        String inText = inputTextArea1.getText();
        String key = generateKey(inText, keyWord);
        geneKeyTextField1.setText(key);
    }//GEN-LAST:event_geneKeyButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVegenere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVegenere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVegenere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVegenere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVegenere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decButton1;
    private javax.swing.JButton encButton1;
    private javax.swing.JButton geneKeyButton1;
    private javax.swing.JTextField geneKeyTextField1;
    private javax.swing.JTextArea inputTextArea1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField keyTextField1;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JTextArea outputTextArea1;
    // End of variables declaration//GEN-END:variables
}
